In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [24]:


url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)
print(df.head())


      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  


In [3]:
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [4]:
# X = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
#        'ptratio', 'b', 'lstat']].values    #feature variable or independent variable i.e. the dataset without the target variable

# or  alternatively use: X = df.drop('medv', axis=1).values
# or  X = df.iloc[:,:-1].values  # all rows, all columns except last column

X = df.drop('medv', axis=1)   # keep as DataFrame
# then train_test_split will return DataFrames and .columns will work

Y = df['medv'].values      #target variable or dependent variable i.e. Median value of owner-occupied homes in $1000's(medv)

In [5]:
Y    

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [7]:
X_train

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
5     0.02985   0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222   
116   0.13158   0.0  10.01     0  0.547  6.176  72.5  2.7301    6  432   
45    0.17142   0.0   6.91     0  0.448  5.682  33.8  5.1004    3  233   
16    1.05393   0.0   8.14     0  0.538  5.935  29.3  4.4986    4  307   
468  15.57570   0.0  18.10     0  0.580  5.926  71.0  2.9084   24  666   
..        ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
106   0.17120   0.0   8.56     0  0.520  5.836  91.9  2.2110    5  384   
270   0.29916  20.0   6.96     0  0.464  5.856  42.1  4.4290    3  223   
348   0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
435  11.16040   0.0  18.10     0  0.740  6.629  94.6  2.1247   24  666   
102   0.22876   0.0   8.56     0  0.520  6.405  85.4  2.7147    5  384   

     ptratio       b  lstat  
5       18.7  394.12   5.21  
116     17.8  393.30  12.04  
45      17.9  396.90  10.21  
16      21.0  386.85   6.58  
468     20.2  368.74  18.13  
..       ...     ...    ...  
106     20.9  395.67  18.66  
270     18.6  388.65  13.00  
348     17.0  390.94   5.99  
435     20.2  109.85  23.27  
102     20.9   70.80  10.63  

[354 rows x 13 columns]

In [8]:
# standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X.columns, index=X_train.index)
X_test  = pd.DataFrame(scaler.transform(X_test),  columns=X.columns, index=X_test.index)
# now this will work

# check the statistics of the standardized data
# it should have mean ~0 and std ~1 because we have standardized it i.e. z = (x - u) / std


In [9]:
X_train


crim        zn     indus      chas       nox        rm       age  \
5   -0.414259 -0.505125 -1.292142 -0.281546 -0.851085  0.145264 -0.365584   
116 -0.402008 -0.505125 -0.162083 -0.281546 -0.087967 -0.208401  0.133941   
45  -0.397211 -0.505125 -0.609489 -0.281546 -0.936828 -0.896237 -1.266900   
16  -0.290936 -0.505125 -0.431970 -0.281546 -0.165136 -0.543965 -1.429789   
468  1.457816 -0.505125  1.005500 -0.281546  0.194987 -0.556496  0.079645   
..        ...       ...       ...       ...       ...       ...       ...   
106 -0.397237 -0.505125 -0.371354 -0.281546 -0.319475 -0.681810  0.836171   
270 -0.381828  0.380752 -0.602272 -0.281546 -0.799639 -0.653963 -0.966462   
348 -0.416046  3.038382 -1.316677 -0.281546 -1.048295  0.430702 -1.415310   
435  0.926113 -0.505125  1.005500 -0.281546  1.566884  0.422348  0.933904   
102 -0.390305 -0.505125 -0.371354 -0.281546 -0.319475  0.110454  0.600888   

          dis       rad       tax   ptratio         b     lstat  
5    1.081628 -0.746179 -1.112790  0.187271  0.396514 -1.015316  
116 -0.487876 -0.398464  0.150088 -0.212090  0.387067 -0.053663  
45   0.628596 -0.746179 -1.046639 -0.167716  0.428541 -0.311324  
16   0.345133 -0.630274 -0.601625  1.207859  0.312760 -0.822422  
468 -0.403892  1.687825  1.557294  0.852872  0.104124  0.803800  
..        ...       ...       ...       ...       ...       ...  
106 -0.732385 -0.514369 -0.138570  1.163486  0.414371  0.878423  
270  0.312349 -0.746179 -1.106776  0.142897  0.333497  0.081504  
348  2.156415 -0.630274 -0.763995 -0.567077  0.359879 -0.905493  
435 -0.773035  1.687825  1.557294  0.852872 -2.878413  1.527504  
102 -0.495130 -0.514369 -0.138570  1.163486 -3.328288 -0.252188  

[354 rows x 13 columns]

In [10]:
X_train.describe()

crim            zn         indus          chas           nox  \
count  354.000000  3.540000e+02  3.540000e+02  3.540000e+02  3.540000e+02   
mean     0.000000 -5.017957e-18  3.763468e-16  1.003591e-17 -6.874601e-16   
std      1.001415  1.001415e+00  1.001415e+00  1.001415e+00  1.001415e+00   
min     -0.416762 -5.051250e-01 -1.432137e+00 -2.815463e-01 -1.477013e+00   
25%     -0.407940 -5.051250e-01 -8.663857e-01 -2.815463e-01 -9.196796e-01   
50%     -0.386964 -5.051250e-01 -2.082672e-01 -2.815463e-01 -1.651363e-01   
75%     -0.022663  3.807519e-01  1.005500e+00 -2.815463e-01  6.322788e-01   
max     10.296908  3.702790e+00  2.396785e+00  3.551814e+00  2.690124e+00   

                 rm           age           dis           rad           tax  \
count  3.540000e+02  3.540000e+02  3.540000e+02  3.540000e+02  3.540000e+02   
mean  -3.512570e-16 -6.774242e-17 -1.405028e-16 -6.272446e-17 -1.756285e-16   
std    1.001415e+00  1.001415e+00  1.001415e+00  1.001415e+00  1.001415e+00   
min   -3.428977e+00 -2.385402e+00 -1.241753e+00 -9.779889e-01 -1.323270e+00   
25%   -6.073179e-01 -8.243866e-01 -7.970573e-01 -6.302741e-01 -7.700089e-01   
50%   -1.366932e-01  3.094984e-01 -3.102052e-01 -5.143691e-01 -4.633100e-01   
75%    4.957956e-01  8.931822e-01  7.700449e-01  1.687825e+00  1.557294e+00   
max    3.417358e+00  1.129371e+00  3.938069e+00  1.687825e+00  1.827911e+00   

            ptratio             b         lstat  
count  3.540000e+02  3.540000e+02  3.540000e+02  
mean   4.014366e-17 -4.541251e-16 -2.508979e-18  
std    1.001415e+00  1.001415e+00  1.001415e+00  
min   -2.519507e+00 -4.140252e+00 -1.505295e+00  
25%   -7.223839e-01  1.967778e-01 -7.826466e-01  
50%    1.428974e-01  3.674826e-01 -2.106528e-01  
75%    8.528718e-01  4.201600e-01  5.355791e-01  
max    1.651593e+00  4.285411e-01  3.597242e+00

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score


In [12]:
regression = LinearRegression()

In [13]:
mse = cross_val_score(regression, X_train, Y_train, scoring='neg_mean_squared_error', cv=5)

In [14]:
mse

array([-24.85792467, -32.34889563, -29.41534458, -18.46226827,
       -24.80445401])

In [15]:
np.mean(mse)  # mean cross-validated MSE

np.float64(-25.977777430926302)

In [16]:
reg_pred = regression.fit(X_train, Y_train).predict(X_test)

In [17]:
reg_pred

array([28.64896005, 36.49501384, 15.4111932 , 25.40321303, 18.85527988,
       23.14668944, 17.3921241 , 14.07859899, 23.03692679, 20.59943345,
       24.82286159, 18.53057049, -6.86543527, 21.80172334, 19.22571177,
       26.19191985, 20.27733882,  5.61596432, 40.44887974, 17.57695918,
       27.44319095, 30.1715964 , 10.94055823, 24.02083139, 18.07693812,
       15.934748  , 23.12614028, 14.56052142, 22.33482544, 19.3257627 ,
       22.16564973, 25.19476081, 25.31372473, 18.51345025, 16.6223286 ,
       17.50268505, 30.94992991, 20.19201752, 23.90440431, 24.86975466,
       13.93767876, 31.82504715, 42.56978796, 17.62323805, 27.01963242,
       17.19006621, 13.80594006, 26.10356557, 20.31516118, 30.08649576,
       21.3124053 , 34.15739602, 15.60444981, 26.11247588, 39.31613646,
       22.99282065, 18.95764781, 33.05555669, 24.85114223, 12.91729352,
       22.68101452, 30.80336295, 31.63522027, 16.29833689, 21.07379993,
       16.57699669, 20.36362023, 26.15615896, 31.06833034, 11.98

In [23]:
sns.displot(Y_test - reg_pred, kind ='kde')  # residuals should be normally distributed

In [19]:
from sklearn.metrics import r2_score

In [20]:
score = r2_score(Y_test, reg_pred)

In [21]:
score

0.7112260057484934

In [22]:
print(regression.predict([[0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14]]))

[-6.64618012]


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
